# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='addres',
            field=models.CharField(max_length=100, null=True, verbose_name='addres'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.CharField(max_length=50, null=True, verbose_name='id_number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(max_length=50, null=True, verbose_name='phone'),
        ),
    ]
